services:

  api:
    container_name: "api-go"
    image: api-server
    ports:
      - "9090:9090"
    environment:
      DATABASE_DSN: postgres://localapi:localapi@postgres:5432/local?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: localapi
      POSTGRES_PASSWORD: localapi
      POSTGRES_DB: local
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - data_local_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localapi -d local"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    volumes:
      - grafa_storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./internal/config/observability/tempo/tempo.yaml:/etc/tempo.yaml
      - ./internal/config/observability/tempo/tempo-data:/var/tempo
    ports:
      - "3200:3200"
  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./internal/config/observability/alloy:/etc/alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    depends_on:
      - tempo
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
volumes:
  grafa_storage:
  data_local_postgres: