// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"

	"apiserver/internal/domain"
	"github.com/google/uuid"
)

type Genres string

const (
	GenresMale   Genres = "male"
	GenresFemale Genres = "female"
)

func (e *Genres) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Genres(s)
	case string:
		*e = Genres(s)
	default:
		return fmt.Errorf("unsupported scan type for Genres: %T", src)
	}
	return nil
}

type NullGenres struct {
	Genres Genres
	Valid  bool // Valid is true if Genres is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenres) Scan(value interface{}) error {
	if value == nil {
		ns.Genres, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Genres.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenres) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Genres), nil
}

type User struct {
	ID        int64
	Uuid      uuid.UUID
	FirstName string
	LastName  string
	Email     string
	DateBirth time.Time
	Genre     domain.Genre
	Password  string
	CreatedAt time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
}
