// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package queries

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
uuid, first_name, last_name, email, genre, date_birth, password
) VALUES (
             $1, $2, $3, $4, $5, $6, $7
         )
RETURNING id, uuid, first_name, last_name, email, date_birth, genre, password, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Uuid      uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Genre     Genres
	DateBirth time.Time
	Password  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Uuid,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Genre,
		arg.DateBirth,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DateBirth,
		&i.Genre,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, uuid, first_name, last_name, email, date_birth, genre, password, created_at, updated_at, deleted_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DateBirth,
		&i.Genre,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, uuid, first_name, last_name, email, date_birth, genre, password, created_at, updated_at, deleted_at FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.DateBirth,
			&i.Genre,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
set first_name = $2, updated_at = $3, last_name = $4, email = $5, password = $6, date_birth = $7, genre = $8
WHERE id = $1
RETURNING id, uuid, first_name, last_name, email, date_birth, genre, password, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID        int64
	FirstName string
	UpdatedAt sql.NullTime
	LastName  string
	Email     string
	Password  string
	DateBirth time.Time
	Genre     Genres
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.UpdatedAt,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.DateBirth,
		arg.Genre,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DateBirth,
		&i.Genre,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
